### ISSUE TITLE
Api Session Renewal

### ISSUE THREAD

**Issue by turecross321** [turecross321/SoundShapesServer#127]

**Comment by jvyden** [comment]
To provide some insight, in oauth this is usually handled with a refresh token, a token that gets shared in addition to the session token when you log in.

The refresh token has the power of being able to generate a session token, and it usually doesn't expire until logout. But I'd keep expire the refresh token after a month or so after inactivity (e.g. each new token generated with the refresh token restarts the expiry timer)

**Comment by turecross321** [comment]
I assume the refresh token also be removed if it's been used once?

**Comment by turecross321** [comment]
Oh wait, my bad - I missed the last part.

**Comment by jvyden** [comment]
I'd look at the OAuth 2.0 standard for the details, this is what I based this system off of.
