### ISSUE TITLE
[Question] Using for a real PS4?

### ISSUE THREAD

**Issue by SevenworksDev** [turecross321/SoundShapesServer#137]
I see that this project is still being developed and I really loved this game but is there any way how to put this on a real PlayStation3/PlayStation4 (no jailbreaking if possible) or if you have plans to do this in the future. I really want to see what the community would look like again and it would be such a cool thing if this is possible.

**Comment by turecross321** [comment]
It is actually already possible to play on private servers on both the PS3 and the PS Vita, but this does require jailbreaking your console, hence this not being viable on PS4. 

The original servers were HTTPS encrypted, which means that you can not simply use a DNS server that redirects traffic to a private server. Instead, you have to modify the game's executable, and this obviously cannot be done on a stock system.

Feel free to join this Sound Shapes discord server if you're interested in the project: https://discord.gg/caYrsdcqwn
