### ISSUE TITLE
How to join?

### ISSUE THREAD

**Issue by PSVitaLover282** [turecross321/SoundShapesServer#289]
Sorry to bother you Ture, but how do you join the server? Can you put a tutorial on how?

**Comment by turecross321** [comment]
Hi, are you trying to connect on PS Vita or PS3/RPCS3?

**Comment by PSVitaLover282** [comment]
PS3 and Vita

**Comment by turecross321** [comment]
Okay, for PS3:

1. Jailbreak your PS3 and install Webman
2. Download https://github.com/LittleBigRefresh/Refresher/releases/tag/v1.5.1
3. Open up Refresher and patch Sound Shapes to https://sound.ture.fish/otg by using the PS3 patch (make sure that it works with autodiscover)
4. Start the game and follow the on screen instructions

For Vita:
it's a bit convoluted at the moment, and I'm eventually going to make a vita plugin that patches it, but basically:

1. follow the following guide up to 2:36 https://youtu.be/ms48Ga24MUo?si=S-86J4vIR-StPNGS
2. download Refresher and patch the eboot.bin.elf file with the url https://sound.ture.fish/otg (make sure that it works with autodiscover)
3. follow the youtube video from 3:51
4. start the game and follow the on screen instructions

**Comment by GIKB7** [comment]
Refresher keeps giving me trouble. It keeps crashing and throwing errors at me. Can I also use UnionPatcher?

**Comment by PSVitaLover282** [comment]
I did all the steps and even though everything went successfully, it gives me an error in the game saying "Unable to log in to the Sound Shapes servers. Would you like to retry?" This is very strange, I do have knowledge of patching games, like LittleBigPlanet, but Sound Shapes just refuses to connect. Even though refresher said "EBOOT successfully patched" and "EBOOT has been patched to https://sound.ture.fish/otg" What is the issue?

**Comment by turecross321** [comment]
if you enter only https://sound.ture.fish and press autodiscover, does it automatically add /otg to the url?

**Comment by PSVitaLover282** [comment]
Yes

**Comment by turecross321** [comment]
i believe that i can see your requests when you used autodiscover, but I don't see any attempts to actually connect to the server after that.

did you update the game after patching or something like that? either way, I'd recommend trying to patch again

**Comment by PSVitaLover282** [comment]
No, my game has always been up-to-date. I'll try again.

**Comment by PSVitaLover282** [comment]
Same error on PS3. Trying on Vita...

**Comment by turecross321** [comment]
okayyy, so ive just tried patching it myself now, and I have come to the conclusion that something here is severely broken. thanks for reporting this, i'll try figuring it out asap

**Comment by PSVitaLover282** [comment]
Alright

**Comment by turecross321** [comment]
i'm still very confused about whats happening, but in the meantime you should be able to patch your game to http://sound.ture.fish/otg (so HTTP not HTTPS)

**Comment by PSVitaLover282** [comment]
Yes! The http instance worked! Thanks a lot!

**Comment by turecross321** [comment]
hell yeah! 👍👍
