### ISSUE TITLE
Add Upload File Limit

### ISSUE THREAD

**Issue by turecross321** [turecross321/SoundShapesServer#41]

**Comment by turecross321** [comment]
I think this should be done with a middleware and the cap shouldnt be more than like 1 megabyte. Maybe more for the API stuff.

**Comment by jvyden** [comment]
It's important to note that the solution implemented here shouldn't be considered a final fix security-wise - I'm pretty sure Bunkum will still allocate all the memory from the request's body. Not to mention, the client can lie about the content length.

A reverse proxy like `nginx` should be used to prevent attacks like this. Not an issue for development, but something to be considered when putting this in production.

**Comment by turecross321** [comment]
Thanks for pointing that out. Would a reverse proxy be seperate from the server?

**Comment by jvyden** [comment]
Yeah, it's a different application entirely. `nginx` probably runs most of the web at this point. It's also what Beacon uses and what I plan to use for Refresh's primary instance in the future.

**Comment by turecross321** [comment]
Right. Do you think I should skip implementing anything like this here then, and assume the person running the server is using nginx?

**Comment by jvyden** [comment]
Perhaps. Can't hurt to have both measures, though. For example you'd want to know if you hit your target filesize during development where you wouldn't be using nginx.

**Comment by turecross321** [comment]
That makes sense, thanks
