### ISSUE TITLE
Game Session Expiration Date might be sent in the wrong format?

### ISSUE THREAD

**Issue by turecross321** [turecross321/SoundShapesServer#72]
The game currently gets the expiration date as a unix time milliseconds timestamp, because thats what the rest of the game uses, but I've experienced that the game doesn't actually throw out an expired session, so there's a chance the the session shouldnt be in milliseconds

**Comment by jvyden** [comment]
It's possible that's intentional and that it doesn't actually care about the expiration - does the game try to reconnect after a 403?

**Comment by turecross321** [comment]
I'll have to look into it more, but I believe so.

**Comment by turecross321** [comment]
Yep, it does.

**Comment by jvyden** [comment]
No, not if it's prompting the user. LBP will do this automatically, but that's because LBP is stupid and weird, I guess.

**Comment by turecross321** [comment]
This is the value of `expires` in the login response taken from the packet captures
`3097117724764`
This is either not unix (sounds improbable) or they literally just made the sessions last for like 50 years so they don't have to handle it

**Comment by turecross321** [comment]
I tried making the server respond with the same expiration date as the original servers did, and everthing appears to work like normal without any new requests. I'm starting to believe that they genuinely just made the sessions never expire.

**Comment by turecross321** [comment]
Actually, the game appears to actually throw out the old session when it has an old expiration date, as oppossed to what it was doing before where it would try to keep using the old one.

**Comment by turecross321** [comment]
Nevermind. Sometimes it tries using the old session again, and sometimes it uses the new one. This game is so weird

**Comment by jvyden** [comment]
Hmm, `3097117724764` just sounds like unix with some sort of epoch. Is there anything relating to authentication in the game's scripts?

**Comment by turecross321** [comment]
Unfortunately not. I did found some login stuff for some an api though, where no expiry date is handled

```lua
finish=function(psnID) {
            this.userName=psnID;

            if (STRINGHELPER_GetLength(psnID)<=0) {
                this.startLogin("need some chars yo!");
                return;
            }
            
            local req=HttpManager.createGetRequest();
            req.setOperation(HTTP_GET);
            req.setURL("http://community.queasygames.com/api/login.php");
            req.addURLParamStr("psnID",psnID);
            req.send();
            
            this.req=req.getID();
GameSystem.trace("sent login request: ",req.getID());
        },
        
        onHttpResponse=function(req) {
GameSystem.trace("got response: ",req.getID());
            if (!?this.reqID||req.getID()!=this.reqID) {
GameSystem.trace("it is login response: ",req.getID());
                //GameSystem.trace("got response: ",req.getResultSize());
                local ok=false;
                if (req.getResultSize()==10) {
                    if (req.getString(0,2)=="ok") {
                        ok=true;
                    }
                }

                if (!ok) {
                    this.startLogin("there was an error!");
                    GameSystem.trace("ERROR:\n"+req.getString(0,req.getResultSize()));
                } else {
                    FILEHELPER_WriteString(this.loginFilename,this.userName,this.loginFileArea);

                    global g_loginData;

                    g_loginData.psnID=this.userName;
                    g_loginData.loginKey=req.getInt32(2);
                    g_loginData.numMyLevels=req.getInt32(2+(3+1));
                    g_loginData.loggedIn=true;
                    
GameSystem.trace("logged in! key is ",g_loginData.loginKey," numLevels=",g_loginData.numMyLevels);
                    this.Process.terminate();

                    g_loginData.signalLogin();
                }
            }
        },
```

**Comment by turecross321** [comment]
After some more testing, I've come to the following conclusion:

The expiry date is already given correctly. The game does not try to reconnect or get a new session automatically, but it does throw out the old session when it gets a 403, if the expiry date has passed.

I am therefore closing this issue.
