### ISSUE TITLE
Optimize Greatest Hits

### ISSUE THREAD

**Issue by turecross321** [turecross321/SoundShapesServer#82]
![image](https://user-images.githubusercontent.com/51852312/237011148-60b92495-3fd2-480d-83d3-04654aeba60e.png)
684ms is crazy

**Comment by turecross321** [comment]
easiest fix would be to just simplify it massively, and make greatest hits just return like the most played levels during the last week

**Comment by turecross321** [comment]
better idea: return all levels sorted by total plays, but only count plays from the past week

**Comment by turecross321** [comment]
I think that solution would require a specific table for plays, but that's fine

**Comment by turecross321** [comment]
actually, nah I'll just make it return the most played levels that were published within the last week. a whole new table for plays is overkill

**Comment by jvyden** [comment]
Refresh has two tables for plays - unique plays and all plays

..So I don't think that's overkill at all, lol

**Comment by turecross321** [comment]
oh damn, i might as well do that here too then

**Comment by turecross321** [comment]
Alright, so this definitely makes the greatest hits sorting better, but how would you order them without having to convert the GameLevel IQueryable to an IEnumerable?

Doing something like this doesn't work without first converting it to an Enumerable, but converting an IQueryable to an IEnumerable absolutely tanks the performance. (I believe it removes the ability to Lazy Load)

```c#
_realm.All<GameLevel>().OrderByDescending(l => l.UniquePlays.Count(r => r.Date > oneWeekAgo))
```
Output
```
System.NotSupportedException: The expression l => l.UniquePlays.Count(r => (r.Date > value(SoundShapesServer.Database.GameDatabaseContext+<>c__DisplayClass47_0).oneWeekAgo)) cannot be used in an Order clause
```
>

Converting it to an IEnumerable
```c#
_realm.All<GameLevel>()
                .AsEnumerable()
                .OrderByDescending(l => l.UniquePlays.Count(r => r.Date > oneWeekAgo))
                .AsQueryable();
```
Output
```
[05-10-23 14:42:08] [Request:Info] <<HandleRequest>d__15:MoveNext> Served request to 192.168.1.134:64147: 200 OK on GET '/otg/~index:level.page?count=9&type=level&search=greatesthits&decorate=completed' (994ms)
```
(works but is extremely slow)

**Comment by turecross321** [comment]
I made it faster by getting the levels from the relations as oppossed to running through every level and checking the plays, and even though this might technically not be very fast, it shouldn't be a problem since it's only getting the relations from the last week.

do you think this works?
```cs
        DateTimeOffset oneWeekAgo = DateTimeOffset.UtcNow.AddDays(-7);
        IQueryable<LevelUniquePlayRelation> relations = _realm.All<LevelUniquePlayRelation>().Where(r=>r.Date > oneWeekAgo);

        var groupedRelations = relations
            .AsEnumerable()
            .Select(lpr => lpr.Level)
            .Distinct()
            .Select(level => new
            {
                Level = level,
                Count = relations.Count(lpr => lpr.Level == level)
            });

        return groupedRelations.OrderByDescending(r => r.Count).Select(r => r.Level).AsQueryable();
```

**Comment by jvyden** [comment]
Yeah, I was gonna suggest doing it the other way around. Should work great from a technical standpoint.

I'm not very performance conscious when it comes to LINQ myself, so it's hard to say performance-wise.

**Comment by turecross321** [comment]
Alright, I'll close the issue. Appreciate the advice 👍
